[tool.poetry]
name = "at3-streamlit-app"
version = "0.0.1"
description = ""
authors = ["Group 3"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11"
pandas = "^2.2.3"
streamlit = "^1.39.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
